[theme]
primaryColor = "#5E6AD2"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#0A0A0B"
font = "sans serif"

[server]
headless = true
maxUploadSize = 10
enableXsrfProtection = true
